// RESPONSE_MAPS coverage: the keys we pay for and the keys we read.
//
// The empty-column defect was the map reading keys the API does not answer with (zero columns, silently,
// on a paid call). Its mirror image is this file's subject: keys the API DOES answer
// with that the map never reads. Both are paid-for-and-lost; only the first one was
// ever guarded. Audited 2026-08-30: zero wrong keys, but 13 unread ones across
// enrich_profile and enrich_company.
//
// Nothing here hardcodes a key list. Every expectation is DERIVED at run time from
// two sources that are regenerated by other tooling:
//
//   _lib/api-catalog.json   the published 200-example key set per endpoint
//                           (`field_map_keys`, generated from the pinned spec)
//   spec/openapi.yaml       the 200 example itself, which is where a key's VALUE
//                           shape (scalar vs `[]`) can be read
//
// so a catalog regen or a spec edit moves these tests with it instead of rotting.
// The only literals are statements of INTENT — the deliberate-omission list and the
// intentionally-shared column names — and pinning intent is the whole point of them.

import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

import YAML from 'yaml';

import {
  RESPONSE_MAPS,
  RESPONSE_KEYS_DELIBERATELY_UNMAPPED,
  RESPONSE_HEADLINE_COLUMNS,
  mapResponse,
  readPath,
} from '../../_lib/client.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..', '..');
const CATALOG_PATH = path.join(ROOT, '_lib', 'api-catalog.json');
const SPEC_PATH = path.join(ROOT, 'spec', 'openapi.yaml');

/**
 * The catalog generator rewrites the catalog; a read that lands mid-write must say so rather than
 * surface as an inscrutable JSON error that looks like a bug in the map.
 */
function readCatalog () {
  const raw = fs.readFileSync(CATALOG_PATH, 'utf8');
  try {
    return JSON.parse(raw);
  } catch (err) {
    assert.fail(
      `_lib/api-catalog.json did not parse (${err.message}). It is regenerated by npm run catalog:gen; `
      + 're-run this suite before treating it as a failure.'
    );
  }
}

const CATALOG = readCatalog();

/** The 200-example key names the catalog publishes for an endpoint. */
function publishedKeys (endpoint) {
  const e = CATALOG.endpoints?.[endpoint];
  assert.ok(e, `${endpoint} is mapped in RESPONSE_MAPS but is not in the catalog`);
  assert.ok(
    Array.isArray(e.field_map_keys) && e.field_map_keys.length > 0,
    `${endpoint} has a hand-written response map and no published response keys — `
    + 'nothing can check the map against anything'
  );
  return e.field_map_keys;
}

/** The keys an endpoint is declared to return-and-not-read, or [] if none are. */
function declaredUnmapped (endpoint) {
  return Object.prototype.hasOwnProperty.call(RESPONSE_KEYS_DELIBERATELY_UNMAPPED, endpoint)
    ? [...RESPONSE_KEYS_DELIBERATELY_UNMAPPED[endpoint]]
    : [];
}

const MAPPED_ENDPOINTS = Object.keys(RESPONSE_MAPS);

/**
 * The spec's own 200 example per operationId — the only place the VALUE of a
 * documented key can be seen, which is what separates "a scalar we could be reading
 * today" from "an array whose element shape nobody has ever recorded".
 */
function specExamples () {
  const doc = YAML.parse(fs.readFileSync(SPEC_PATH, 'utf8'));
  const out = {};
  for (const item of Object.values(doc.paths ?? {})) {
    for (const op of Object.values(item ?? {})) {
      const id = op?.operationId;
      const ex = op?.responses?.['200']?.content?.['application/json']?.example;
      if (id && ex && typeof ex === 'object' && !Array.isArray(ex)) out[id] = ex;
    }
  }
  return out;
}

const EXAMPLES = specExamples();

const LIVE_DIR = path.join(ROOT, 'tests', 'fixtures', 'live');

/**
 * The RECORDED response for an endpoint, or null when none was captured.
 *
 * This is the source of truth that replaced the spec examples on 2026-09-02. Only a
 * 200 counts: the capture run also recorded 4xx bodies, and a 422 says nothing about
 * the shape of a successful answer.
 */
function liveCapture (endpoint) {
  const p = path.join(LIVE_DIR, `${endpoint}.json`);
  if (!fs.existsSync(p)) return null;
  const f = JSON.parse(fs.readFileSync(p, 'utf8'));
  if (f.http_status !== 200 || !f.body || typeof f.body !== 'object') return null;
  return f;
}

function exampleFor (endpoint) {
  const ex = EXAMPLES[endpoint];
  assert.ok(ex, `spec/openapi.yaml has no 200 example object for ${endpoint}`);
  return ex;
}

const isScalarExample = (v) => v !== null && typeof v !== 'object';
const isEmptyArrayExample = (v) => Array.isArray(v) && v.length === 0;

// ---------------------------------------------------------------------------
// 1. The empty-column regression guard: nothing in the map is unreachable.
// ---------------------------------------------------------------------------

test('every RESPONSE_MAPS key is a key the endpoint actually publishes', () => {
  const offenders = [];
  for (const endpoint of MAPPED_ENDPOINTS) {
    const keys = publishedKeys(endpoint);
    for (const k of Object.keys(RESPONSE_MAPS[endpoint])) {
      if (!keys.includes(k)) offenders.push(`${endpoint}.${k}`);
    }
  }
  assert.deepEqual(
    offenders, [],
    'a map key the API does not answer with is a column that silently never populates '
    + 'on a paid call — a failure that shipped once already'
  );
});

// ---------------------------------------------------------------------------
// 2. The mirror: nothing the API publishes is silently unread.
// ---------------------------------------------------------------------------

test('mapped keys + declared omissions == the published key set, exactly', () => {
  // The invariant that makes an omission a DECISION. A published key must be either
  // read into a column or named in RESPONSE_KEYS_DELIBERATELY_UNMAPPED; it can never
  // be absent from both, which is the state 13 keys were in before this check.
  for (const endpoint of MAPPED_ENDPOINTS) {
    const published = [...publishedKeys(endpoint)].sort();
    const mapped = Object.keys(RESPONSE_MAPS[endpoint]);
    const omitted = declaredUnmapped(endpoint);

    const overlap = mapped.filter((k) => omitted.includes(k));
    assert.deepEqual(overlap, [],
      `${endpoint} both maps and declares-unmapped: ${overlap.join(', ')} — pick one`);

    const covered = [...new Set([...mapped, ...omitted])].sort();
    assert.deepEqual(covered, published,
      `${endpoint}: the union of what the pack reads and what it declares it does not `
      + 'read must equal what the API returns. A key in neither list is a paid field '
      + 'nobody decided about.');
  }
});

test('the omission list only names endpoints and keys that actually exist', () => {
  for (const endpoint of Object.keys(RESPONSE_KEYS_DELIBERATELY_UNMAPPED)) {
    assert.ok(MAPPED_ENDPOINTS.includes(endpoint),
      `${endpoint} declares unread keys but has no RESPONSE_MAPS entry at all — an `
      + 'endpoint with no map is reported as MAP_NO_MAP, not as a partial read');
    const published = publishedKeys(endpoint);
    for (const k of declaredUnmapped(endpoint)) {
      assert.ok(published.includes(k),
        `${endpoint} declares "${k}" unread, but the endpoint does not publish it — a `
        + 'stale omission hides a real gap by making the coverage test pass');
    }
  }
});

// ---------------------------------------------------------------------------
// 3. The omission list is exactly the fields whose shape is unrecorded.
// ---------------------------------------------------------------------------

test('everything declared unread is a path the server really answered with', () => {
  // REWRITTEN 2026-09-02. The old justification was "it is an empty array in the spec
  // example, so its element shape is unrecorded". That reason is spent: 35 endpoints
  // now carry recorded live shapes, so an omission can no longer hide behind an absent
  // example. What survives is the part that always mattered — an omission must name a
  // path the endpoint ACTUALLY returns, or it is a stale entry making the coverage
  // invariant pass while a real gap sits behind it.
  for (const endpoint of Object.keys(RESPONSE_KEYS_DELIBERATELY_UNMAPPED)) {
    const published = publishedKeys(endpoint);
    for (const k of declaredUnmapped(endpoint)) {
      assert.ok(published.includes(k),
        `${endpoint}.${k} is declared unread, but the endpoint does not publish it. `
        + 'A stale omission hides a real gap by making the coverage test pass.');
    }
  }
});

test('no scalar the endpoint returns is left unread', () => {
  // The generalisation of the gap this check closed: a recorded scalar is a column the
  // pack could deliver today at no extra cost, because the call was already paid for.
  // Now that `publishedKeys` is live-derived for absorbed endpoints, this is a check
  // against what the SERVER answers rather than what the spec claims — which is the
  // whole point of the absorption.
  const unread = [];
  for (const endpoint of MAPPED_ENDPOINTS) {
    const mapped = Object.keys(RESPONSE_MAPS[endpoint]);
    const omitted = declaredUnmapped(endpoint);
    for (const k of publishedKeys(endpoint)) {
      if (mapped.includes(k) || omitted.includes(k)) continue;
      unread.push(`${endpoint}.${k}`);
    }
  }
  assert.deepEqual(unread, [],
    'these paths are scalars the API returns on a call the user already paid for, and '
    + 'the pack throws them away. Map them, or state why not.');
});

// ---------------------------------------------------------------------------
// 4. The added keys behave: RECORDED bodies produce the named columns.
// ---------------------------------------------------------------------------

test('the recorded live body produces every mapped column', () => {
  // THE REGRESSION GUARD FOR THE 2026-09-02 REWRITE. Replay each endpoint's actual
  // recorded response through mapResponse and assert every mapped path resolves. This
  // is the test that would have caught the failure it was written for: against the
  // real email_finder body, the old map produced 1 column of 3 and the email was gone.
  //
  // Built from the recordings rather than from the spec examples, because the spec
  // examples are what got this wrong. A path that stops resolving fails here.
  const skipped = [];
  for (const endpoint of MAPPED_ENDPOINTS) {
    const cap = liveCapture(endpoint);
    if (!cap) { skipped.push(endpoint); continue; }
    const map = RESPONSE_MAPS[endpoint];
    const cols = mapResponse(endpoint, cap.body);
    const missing = Object.entries(map)
      .filter(([p]) => readPath(cap.body, p) !== undefined)
      .filter(([, col]) => !Object.prototype.hasOwnProperty.call(cols, col))
      .map(([p, col]) => `${p} -> ${col}`);
    assert.deepEqual(missing, [],
      `${endpoint}: these paths resolve in the recorded response but produced no column`);
    assert.ok(Object.keys(cols).length > 0,
      `${endpoint}: the recorded 200 response produced ZERO columns — a billed call `
      + 'that delivers nothing');
  }
  assert.deepEqual(skipped, [],
    'every mapped endpoint must have a recorded live capture to check its map against. '
    + 'A map with no recording behind it is the state that produced the 2026-09-02 defect.');
});

test('the waterfall delivers the field each hop is paid for', () => {
  // The blunt version, named by column. These are the fields a GTM user buys: an
  // email, a phone number, a verification verdict, a name and a title. Each is pinned
  // by name because a rename downstream is a breaking change, not a refactor — and
  // because on 2026-09-01 every one of them was silently absent.
  const WANT = {
    enrich_profile: ['first_name', 'last_name', 'title', 'company_name', 'company_domain', 'linkedin_url', 'location'],
    enrich_company: ['company_name', 'company_website', 'company_industry', 'company_size', 'hq_city'],
    email_finder: ['email', 'email_status'],
    email_verifier: ['email_verification_status'],
    phone_finder: ['phone'],
    identify_email_type: ['email_domain', 'email_is_company'],
    find_personal_email: ['personal_email'],
    // 2026-09-17: the live post-engagers run paid for post_details and got `{}`.
    post_details: ['post_urn', 'post_comment_count', 'post_reaction_count', 'post_author_urn'],
  };
  for (const [endpoint, columns] of Object.entries(WANT)) {
    const cap = liveCapture(endpoint);
    assert.ok(cap, `${endpoint} has no recorded capture to check`);
    const cols = mapResponse(endpoint, cap.body);
    for (const c of columns) {
      assert.ok(Object.prototype.hasOwnProperty.call(cols, c),
        `${endpoint} was paid for and did not deliver "${c}". This is the exact defect `
        + 'fixed on 2026-09-02: the map read the spec, the server answered differently, '
        + 'and the user paid for a column that never appeared.');
    }
  }
});

test('every mapped endpoint names the column it is bought for', () => {
  // RESPONSE_HEADLINE_COLUMNS is what lets inspectResponse tell a partial read from a
  // clean one. A mapped endpoint with no headline silently opts out of that check, so
  // the absence has to be impossible rather than merely discouraged.
  for (const endpoint of MAPPED_ENDPOINTS) {
    const headline = RESPONSE_HEADLINE_COLUMNS[endpoint];
    assert.ok(headline,
      `${endpoint} is mapped but names no headline column — a partial read of it can `
      + 'never be detected, which is how the email_finder failure stayed invisible');
    assert.ok(Object.values(RESPONSE_MAPS[endpoint]).includes(headline),
      `${endpoint}'s headline column "${headline}" is not one this map produces`);
  }
});

// ---------------------------------------------------------------------------
// 5. Column collisions across hops, which is how a good column becomes a wrong one.
// ---------------------------------------------------------------------------

test('two endpoints share an output column only where that is intended', () => {
  // A row is enriched by several endpoints and the columns merge into one record
  // (`{...prior, ...mapped}`), so two endpoints writing the same column name means the
  // later hop overwrites the earlier. `follower_count` (person) vs
  // `company_follower_count` (employer) is exactly this hazard, which is why the
  // company map carries the prefix. Any NEW shared name has to be declared here.
  const INTENTIONALLY_SHARED = {
    // Same concept from either side of the waterfall: the profile hop reads the
    // employer off the current position, the company hop reads it off the company
    // record. Either may run first; both mean the same thing.
    company_name: ['enrich_profile', 'enrich_company'],
    // The profile hop gets the employer's LinkedIn page from the position's company
    // record; the company hop gets it from the company itself. Same page.
    company_linkedin_url: ['enrich_profile', 'enrich_company'],
    // NOTE 2026-09-02: `email` is no longer shared. It used to be claimed by both
    // email_finder and email_verifier, on the theory that the verifier echoes the
    // address it checked. The recorded verifier response does not echo it at all — it
    // answers `result.status` and nothing else — so the sharing was describing a shape
    // that never existed. The verifier's verdict is now `email_verification_status`,
    // which is a different fact from the finder's `email_status` (the ESP's view) and
    // must not overwrite it.

    // ADDED 2026-09-17 with the 21 new maps. Each of these is the SAME FACT read off a
    // different endpoint, which is why they share a name instead of carrying a prefix:
    // website_intelligence is an aggregate that runs the web_* modules internally, so
    // its meta-tag / tech-stack / pixel / JSON-LD fields are those modules' fields; a
    // sitemap's URL count is the same count whichever endpoint fetched it; and a
    // YouTube channel's name is the channel's name. Whichever hop runs last writes the
    // value, and both hops mean the same thing by it.
    canonical_url: ['web_meta_tags', 'website_intelligence'],
    favicon_url: ['web_meta_tags', 'website_intelligence'],
    json_ld_block_count: ['web_json_ld', 'website_intelligence'],
    og_image: ['web_meta_tags', 'website_intelligence'],
    og_site_name: ['web_meta_tags', 'website_intelligence'],
    page_description: ['web_meta_tags', 'website_intelligence'],
    page_title: ['web_meta_tags', 'web_scrape', 'website_intelligence'],
    pixels_found_count: ['web_pixels', 'website_intelligence'],
    sitemap_first_url: ['find_sitemap_urls', 'web_sitemap'],
    sitemap_url_count: ['find_sitemap_urls', 'web_sitemap'],
    tech_company_stage: ['web_tech_stack', 'website_intelligence'],
    tech_monthly_spend_estimate: ['web_tech_stack', 'website_intelligence'],
    top_technology: ['web_tech_stack', 'website_intelligence'],
    top_technology_category: ['web_tech_stack', 'website_intelligence'],
    top_technology_confidence: ['web_tech_stack', 'website_intelligence'],
    youtube_channel_name: ['youtube_channel', 'youtube_channel_videos'],
  };

  const byColumn = new Map();
  for (const endpoint of MAPPED_ENDPOINTS) {
    for (const column of Object.values(RESPONSE_MAPS[endpoint])) {
      if (!byColumn.has(column)) byColumn.set(column, []);
      byColumn.get(column).push(endpoint);
    }
  }

  const shared = {};
  for (const [column, endpoints] of byColumn) {
    if (endpoints.length > 1) shared[column] = endpoints.sort();
  }
  for (const v of Object.values(INTENTIONALLY_SHARED)) v.sort();

  assert.deepEqual(shared, INTENTIONALLY_SHARED,
    'an undeclared shared column means one hop silently overwrites another hop\'s '
    + 'value for a different concept. Rename it, or declare the sharing here.');
});

// ---------------------------------------------------------------------------
// 6. find_personal_email stays unmapped, and stays undeclared.
// ---------------------------------------------------------------------------

test('find_personal_email is mapped off the recording that settled its shape', () => {
  // RESOLVED 2026-09-02. This endpoint was deliberately unmapped for as long as the
  // spec (an async envelope `{data, id, status}`) and the backend's generated manifest
  // (a resolved payload `{first_personal_email, message}`) disagreed about what it
  // returns — mapping either would have been wrong against the other, so it reported
  // MAP_NO_MAP and stayed loud.
  //
  // The capture settles it. The server answers the envelope, resolved:
  // `{id, data:{email, status, verifier}, status}`. A recording outranks two
  // disagreeing documents (law 6), so the map exists now — and this is a PAID endpoint
  // that until this change delivered no columns at all.
  const cap = liveCapture('find_personal_email');
  assert.ok(cap, 'the map rests on a recording; without it this endpoint goes back to unmapped');
  assert.ok(RESPONSE_MAPS.find_personal_email, 'find_personal_email is mapped');
  assert.equal(readPath(cap.body, 'data.email') !== undefined, true,
    'the recorded shape is the async envelope, resolved — `data.email`, not `first_personal_email`');
  const cols = mapResponse('find_personal_email', cap.body);
  assert.ok(cols.personal_email, 'the recorded response yields the address it was paid for');
  assert.ok(cols.personal_email_status, 'and the status that says whether it is usable');
});

// ---------------------------------------------------------------------------
// 7. The tables stay frozen.
// ---------------------------------------------------------------------------

test('the omission list is frozen, like the map it documents', () => {
  assert.ok(Object.isFrozen(RESPONSE_KEYS_DELIBERATELY_UNMAPPED));
  for (const v of Object.values(RESPONSE_KEYS_DELIBERATELY_UNMAPPED)) {
    assert.ok(Object.isFrozen(v), 'a mutable omission list can be emptied at run time');
  }
});
